# These are supported funding model platforms
github:['aissat']
liberapay:aissat
open_collective:['aissat-abdelwahab']
custom: ['https://paypal.me/aissatabdelwahab','https://www.paypal.me/aissatabdo']
